import Head from 'next/head'
// import Image from 'next/image'
// import Game from '../components/tapeTaupe/'
import MenuNav from './MenuNav'


export default function Default({children, color}) {
  return (
    <div>
      <Head>
        <title>My Tape Taupe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
      </Head>

      <MenuNav/>  

      {children}
      
      
    </div>
  )
}
